#!/usr/bin/env fish

function switch_to
    set argc $(count $argv)
    if [ $argc -lt 1 ]
        echo "Usage: $(status filename) <session-name>" >&2
        return 1
    end

    if [ -n "$TMUX" ]
        tmux switch-client -t $argv[1]
    else
        tmux attach-session -t $argv[1]
    end
end

set argc $(count $argv)
if [ $argc -gt 0 ]
    set selected $argv[1]
    set selected $(realpath $selected)
    if ! zoxide query "$selected"
        zoxide add "$selected"
    end
else
    set selected $(zoxide query --interactive)
end

if [ -n $selected ]
    set sessions $(tmux list-sessions)
    if ! echo "$sessions" | grep -E "^$selected:"
        tmux new-session -ds $selected -c $selected
    end
    switch_to $selected
end

